title = "Perth Linux Users Group"
baseURL = "https://www.plug.org.au/"
languageCode = "en-au"
disablePathToLower = true
enableGitInfo = true
enableRobotsTXT = true

[pagination]
pagerSize = 50

[params]
github_username = "plugorgau"
twitter_username = "plugorgau"

[markup.goldmark.renderer]
unsafe = true

[permalinks]
minutes = "/events/committee/:year/:month-:day/"

[taxonomies]
presenter = "presenters"
