name: gh-pages

on:
  push:
    branches: [master, main]
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Allow workflow to deploy to pages
permissions:
  contents: read
  pages: write
  id-token: write

# Cancel in-progress jobs
concurrency:
  group: pages
  cancel-in-progress: true

env:
  TZ: Australia/Perth
  GIT_CONFIG_NOSYSTEM: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Hugo
        run: sudo snap install --channel=extended/stable hugo
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Configure git identity
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Build site
        run: hugo --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
